name: Build ChainSawCLI with flake.nix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        system: [ x86_64-linux ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: experimental-features = nix-command flakes

      - name: Build flake.nix
        run:
          nix build .#packages.${{ matrix.system }}.default